<?php

	function getDivisi() {
    return array(
    	'SPV',
      'CCO',
      'SA',
      'KOOR SA',
      'FO MANAGER',
      'CCO MANAGER',
      'SALES MANAGER',
      'SERVICE MANAGER',
      'GENERAL MANAGER',
      'ACCOUNTING MANAGER',
      'ASST SERVICE MANAGER',
      'SA BP',
      'ADMIN BP',
      'ADMIN PART BP',
      'TRAINER',
      'ADMIN PART',
      'ADMIN SALES',
      'ADMIN DISTRIBUSI',
      'IT',
      'UMUM',
      'FO',
      'MAINTENANCE',
      'ACCOUNTING',
      'KEUANGAN',
      'VALIDASI',
      'PART MANAGER',
      'MEKANIK',
      'ADMIN SERVICE',
      'STAFF SALVAGE',
      'MARKETING SUPPORT',
      'MOTORIS',
      'MEKANIK BP',
      'DRIVER',
      'PIC PAMERAN',
      'ADMIN GUDANG',
      'KETOK',
      'DEMPUL',
      'CUCI',
      'MASKING',
      'CAT',
      'TINTER',
      'POLES',
      'RAKIT',
      'KEBERSIHAN',
      'GESEK UNIT',
      'PAMERAN',
      'PIC PAMERAN',
      'PIC TESTDRIVE',
      'PDI',
      'PDI SHOWROOM',
      'SATPAM',
      );
    }

    function GenerateUsers() {
    	return [
    		'3048' => ['SONI', 'ACCOUNTING'],
    		'4006' => ['WAHYU DEDI', 'ACCOUNTING MANAGER'],
    		'3023' => ['REKSA ALEX', 'ASST HEAD PRODUKSI'],
    		'5040' => ['SUSANTI', 'KOOR ADM BAHAN'],
    		'3090' => ['BAYU BASUKI', 'MANAGER BP'],
    		'1393' => ['ENDARTI SISWATI', 'HEAD ADMIN BP'],
    		'3012' => ['ANITA PUSPITA DEWI', 'KOOR ADMIN SALES'],
    		'3085' => ['FITRI SURYANI', 'VALIDASI'],
    		'3061' => ['M. ALAM FRADIKA', 'ADMIN SALES'],
    		'3056' => ['SYALSHADILLA OESMAN', 'ADMIN SALES'],
    		'3037' => ['AMILIA GULIA WIBISANA', 'MANAGER CCO'],
    		'3053' => ['DENI SUDRAJAT', 'CCO'],
    		'3043' => ['FANNY SITI KHOIRUNISA', 'CCO'],
    		'8011' => ['LISNAWATI AGUSTIN', 'CCO'],
    		'3057' => ['MARISSA YUNIAR FIRDAUS', 'CCO'],
    		'8008' => ['MELISAH ZIMI SUTARYAT', 'CCO'],
    		'8012' => ['SARAH NURLAILA FAUZIAH', 'CCO'],
    		'8009' => ['SHIERLY GABRIELA', 'KOOR CCO'],
    		'3084' => ['TYASUCI RAHAYU', 'CCO'],
    		'4065' => ['DICKY', 'DESIGNER'],
    		'1024' => ['FEMMY FINILAWATI SAPTARIANI', 'DISTRIBUSI'],
    		'1012' => ['JASON CHRISTIANTO', 'DISTRIBUSI'],
    		'3083' => ['MUHAMMAD PURWANDI', 'DISTRIBUSI'],
    		'3039' => ['AGUNG PRASETYO', 'FIELD OPERATION'],
    		'3042' => ['FIFIN FARDANI', 'FIELD OPERATION'],
    		'4106' => ['INEU ROSE', 'FO MANAGER'],
    		'4016' => ['WAHIDIN CAHYONO', 'KOOR GUDANG'],
    		'3032' => ['NISSA YUSIANA GANI', 'HRD'],
    		'3059' => ['RIA SATRIANI DEWI', 'HRD'],
    		'3054' => ['ABDUL HARIS', 'IT PROGRAMMER'],
    		'1026' => ['KRISNA TIARSWENDO', 'IT NETWORK'],
    		'3069' => ['RIDHWAN HADIYAN', 'KOOR IT'],
    		'6007' => ['ELIN MALINDA', 'KOOR KEUANGAN'],
    		'8000' => ['FAJARIAH AMANAH MUSTOFA', 'ADMIN KEUANGAN'],
        '3082' => ['AJENG RAHMAWATI', 'ADMIN KEUANGAN'],
    		'3036' => ['SITI RISDA', 'ADMIN KEUANGAN'],
    		'3055' => ['ANGGI AKBAR', 'MARKETING SUPPORT'],
    		'1007' => ['GUGUN GUNAWAN', 'KOOR SA BP'],
    		'1009' => ['ARI KHAERUL UMAM', 'ASST SALES MANAGER'],
    		'3050' => ['CEPI', 'SALES'],
    		'1293' => ['CHRISTINA MARIA ANDRIANI', 'ASST SALES MANAGER'],
    		'5016' => ['ARI KARTONO', 'KOOR SA'],
    		'5008' => ['IFFA NUR FALINNA', 'ASST SERVICE MANAGER'],
        '2024' => ['ASEP PURNAMA', 'SERVICE MANAGER'],
    		'2026' => ['SIGIT', 'PART MANAGER'],
    		'3680' => ['DARMAJAYA', 'MAINTENANCE'],
    		'4075' => ['NANANG KUSMANTO', 'KOOR UMUM']
    		
    	];
    }

    function EmployeeAbest() {
      return [
        '4250' => ['CEPI SUNANDAR', 'SALES MANAGER'],
        '1005' => ['DIAN ANDRIANI', 'ASS SALES MANAGER'],
        '1026' => ['WAHYUDI', 'ASS SALES MANAGER'],
        '8007' => ['ASEP CAHYADI', 'SERVICE MANAGER'],
        '2072' => ['CECEP SOMANTRI M', 'ASS SERVICE MANAGER'],
        '2022' => ['FERDIOKA', 'PART MANAGER'],
        '4052' => ['ACHMAD FAIZAL S', 'DISTRIBUSI'],
        '4045' => ['SITI NURFADILAH', 'KOOR ADM SALES'],
        '3006' => ['SUSILANINGSIH', 'KOOR KEUANGAN'],
        '2086' => ['ARIP HARYANTO', 'UMUM'],
        '4128' => ['IRWAN MULYANA', 'UMUM'],
        '2033' => ['RICKY ADJIE Y', 'TRAINER'],
        '4004' => ['IDEN', 'ADM SERVICE'],
        '2039' => ['JUMEGI ARDIANSYAH', 'KOOR SA'],
        '4018' => ['DIAH SUCI A', 'KOOR CCO'],
        '8003' => ['MUHAMMAD ABDUKH S.', 'FOREMAN'],
        '4024' => ['REZKI MUDA P', 'KOOR GUDANG'],
        '6049' => ['IIN ABDUL ROHIM', 'MEKANIK CUCI'],
        '2089' => ['RIZAL MAULANA Y', 'MEKANIK CUCI'],
        '2023' => ['ANTON SOIMUN', 'ADMIN PART'],
        '2046' => ['M. DENDI JUNAEDI', 'SA'],
        '8005' => ['ANGGARA RAKA N.', 'MEKANIK'],
        '2005' => ['FAJAR AHMAD S.', 'MEKANIK'],
        '0605' => ['M. SYARIPUDIN', 'MEKANIK'],
        '0603' => ['ZAFAR ASH SHIDIQ', 'MEKANIK'],
        '2214' => ['MELLY OKTARI', 'CCO'],
      ];
    }

    function DataPosition() {
      return array(
        'SPV',
        'CCO',
        'SA',
        'KOOR SA',
        'FO MANAGER',
        'CCO MANAGER',
        'SALES MANAGER',
        'SERVICE MANAGER',
        'GENERAL MANAGER',
        'ACCOUNTING MANAGER',
        'ASST SERVICE MANAGER',
        'SA BP',
        'ADMIN BP',
        'ADMIN PART BP',
        'TRAINER',
        'ADMIN PART',
        'ADMIN SALES',
        'ADMIN DISTRIBUSI',
        'IT',
        'FO',
        'UMUM',
        'MAINTENANCE',
        'ACCOUNTING',
        'KEUANGAN',
        'VALIDASI',
        'PART MANAGER',
        'MEKANIK',
        'ADMIN SERVICE',
        'STAFF SALVAGE',
        'MARKETING SUPPORT',
        'MOTORIS',
        'MEKANIK BP',
        'DRIVER',
        'PIC PAMERAN',
        'ADMIN GUDANG',
        'KETOK',
        'DEMPUL',
        'CUCI',
        'MASKING',
        'CAT',
        'TINTER',
        'POLES',
        'RAKIT',
        'KEBERSIHAN',
        'GESEK UNIT',
        'PAMERAN',
        'PIC PAMERAN',
        'PIC TESTDRIVE',
        'PDI',
        'PDI SHOWROOM',
        'SATPAM',
      );
    }
